#!/bin/bash

set -e

CATALINA_HOME='/usr/share/apache-tomcat-8.0.47'
SERVER_HTTP_PORT='80'

TEMP_STAGING_DIR='/your_directory_upload_file_war/codedeploy/'
WAR_STAGED_LOCATION="$TEMP_STAGING_DIR/SpringMVCHibernateCRUD.war"
HTTP_PORT_CONFIG_XSL_LOCATION="$TEMP_STAGING_DIR/configure_http_port.xsl"

CONTEXT_PATH='your_project_name'
# Remove unpacked application artifacts
if [[ -f $CATALINA_HOME/webapps/$CONTEXT_PATH.war ]]; then
    rm $CATALINA_HOME/webapps/$CONTEXT_PATH.war
fi
if [[ -d $CATALINA_HOME/webapps/$CONTEXT_PATH ]]; then
    rm -rfv $CATALINA_HOME/webapps/$CONTEXT_PATH
fi

# Copy the WAR file to the webapps directory
cp $WAR_STAGED_LOCATION $CATALINA_HOME/webapps/$CONTEXT_PATH.war


service tomcat start

